services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 80:5173
    volumes:
      - ./frontend/:/app
    networks:
      - todo-manager
  
  backend:
    build: ./backend
    container_name: backend
    ports:
      - 3030:3030
    volumes:
      - ./backend/:/app
    networks:
      - todo-manager

  database:
    image: mysql
    container_name: database
    ports:
      - 3306:3306
    attach: false
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: mysql
      MYSQL_DATABASE: todo_manager
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - todo-manager

networks:
  todo-manager:
    driver: bridge