services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 80:5173
    volumes:
      - ./frontend/:/app
    networks:
      - todo-manager
  
  backend:
    build: ./backend
    container_name: backend
    ports:
      - 3030:3030
    volumes:
      - ./backend/:/app
    networks:
      - todo-manager

networks:
  todo-manager:
    driver: bridge